daemon:
  # Path to logfile
  logFile: /var/log/bpfcontain.log
  # Path to pidfile
  pidFile: /run/bpfcontain.pid
  # Working directory
  workDir: /var/lib/bpfcontain
  # Log level
  verbosity: INFO

policy:
  # Path to policy directory
  dir: /var/lib/bpfcontain/policy
